* csvq emacs extension

This package is a emacs extension for [[csvq (https://github.com/mithrandie/csvq).]]

* Variables

- csvq-log-buffer
  Buffer name to write logs or csvq execution.
- csvq-default-format
  Default format for the csvq-insert function.

* Functions

- csvq
  Execute csvq and write the results to the csvq-log-buffer.
- csvq-insert
  Execute csvq and insert the results to the current buffer.
- csvq-org-replace
  Execute csvq to the current Org-mode table and replace the table with the results.
- csvq-org-update
  Execute csvq to the current Org-mode table and replace the table with the auto-selected result.
- csvq-with-options
  Execute csvq with specific options and write the results to the csvq-log-buffer.
- csvq-insert-with-options
  Execute csvq with specific options and insert the results to the current buffer.
- csvq-insert-csv
  Execute csvq and insert the results to the current buffer. The result-sets are formatted in CSV.
- csvq-insert-tsv
  Execute csvq and insert the results to the current buffer. The result-sets are formatted in TSV.
- csvq-insert-json
  Execute csvq and insert the results to the current buffer. The result-sets are formatted in JSON.
- csvq-insert-jsonh
  Execute csvq and insert the results to the current buffer. The result-sets are formatted in JSON with hexadecimal escape sequences.
- csvq-insert-jsona
  Execute csvq and insert the results to the current buffer. The result-sets are formatted in JSON with hexadecimal escape sequences for all characters.
- csvq-insert-gfm
  Execute csvq and insert the results to the current buffer. The result-sets are formatted in GitHub Flavored Markdown.
- csvq-insert-org
  Execute csvq and insert the results to the current buffer. The result-sets are formatted in Org-mode table.
- csvq-insert-text
  Execute csvq and insert the results to the current buffer. The result-sets are formatted in text table.
